### PR TITLE
Close button

### PR DESCRIPTION
**Pull request by vangoo**
Close event div

### CODE REVIEW

**Comment by kkalbaugh** [comment]
I would like to second adding this.

**Comment by kthornbloom** [comment]
Hey guys. Might not be obvious enough, but when you enter the event list, a little calendar icon appears which you click to get back to the calendar. 

closebtn

**Comment by vangoo** [comment]
my god man r u serious =) hahahah

**Comment by kthornbloom** [comment]
Probably should make it more noticeable!!

**Comment by vangoo** [comment]
maybe close icon or write  'close'.

**Comment by vangoo** [comment]
u dont click the href on second one

**Comment by vangoo** [comment]
@kthornbloom u can try second one? i think its so good.

**Comment by vangoo** [comment]
monthly-cal class is close just but mine clear monthly-event-list class @kthornbloom

**Comment by kkalbaugh** [comment]
@kthornbloom @vangoo   I saw the close link, but I wasn't as lucky with user testing...  users missed it more than half the time.   

Regardless,  awesome work and appreciate you sharing it!

**Comment by kthornbloom** [comment]
I'm going to go ahead and close this but thank you for bringing it up! I will be making updates shortly which will include making that button more visible.

**Pull request closed without merging**
